var LocalizedStrings = require("../CommonModules/LocalizedStrings");
let MHLocalizableString = new LocalizedStrings({
 "en":{
   setting:"setting",
   featureSetting:"Shortcut settings",
   commonSetting:"Common settings",
   deviceName:"Device name",
   locationManagement:"Locations",
   shareDevice:"Share device",
   ifttt:"Automation",
   firmwareUpgrate:"Check for firmware updates",
   moreSetting:"Additional settings",
   addToDesktop:"Add to Home screen",
   resetDevice:"Remove device",
   licenseAndPolicy:"User Agreement & Privacy Policy",

 },
 "zh-Hans":{
   setting:"设置",
   featureSetting:"功能设置",
   commonSetting:"通用设置",
   deviceName:"设备名称",
   locationManagement:"位置管理",
   shareDevice:"设备共享",
   ifttt:"智能",
   firmwareUpgrate:"检查固件升级",
   moreSetting:"更多设置",
   addToDesktop:"添加到桌面",
   resetDevice:"删除设备",
   licenseAndPolicy:"使用条款和隐私政策",
 },
 "zh-Hant": {
   setting:"設置",
   featureSetting:"功能設定",
   commonSetting:"一般設定",
   deviceName:"裝置名稱",
   locationManagement:"位置管理",
   shareDevice:"裝置共用",
   ifttt:"智慧",
   firmwareUpgrate:"檢查韌體更新",
   moreSetting:"更多設定",
   addToDesktop:"新增到桌面",
   resetDevice:"刪除裝置",
   licenseAndPolicy:"用戶協議和隱私政策",
 },
 "zh-HK":{
   setting:"設置",
   featureSetting:"feature setting",
   commonSetting:"一般設定",
   deviceName:"裝置名稱",
   locationManagement:"位置管理",
   shareDevice:"裝置共用",
   ifttt:"智慧",
   firmwareUpgrate:"檢查韌體更新",
   moreSetting:"更多設定",
   addToDesktop:"新增到桌面",
   resetDevice:"刪除裝置",
   licenseAndPolicy:"用戶協議和隱私政策",
 },
 "zh-TW":{
   setting:"設置",
   featureSetting:"feature setting",
   commonSetting:"一般設定",
   deviceName:"裝置名稱",
   locationManagement:"位置管理",
   shareDevice:"裝置共用",
   ifttt:"智慧",
   firmwareUpgrate:"檢查韌體更新",
   moreSetting:"更多設定",
   addToDesktop:"新增到桌面",
   resetDevice:"刪除裝置",
   licenseAndPolicy:"用戶協議和隱私政策",
 },
 "krea":{
   featureSetting:"바로가기 설정",
   commonSetting:"일반 설정",
   deviceName:"기기 이름",
   locationManagement:"위치",
   shareDevice:"기기 공유",
   ifttt:"자동화",
   firmwareUpgrate:"펌웨어 업데이트 확인",
   moreSetting:"추가 설정",
   addToDesktop:"홈 화면에 추가",
   resetDevice:"기기 제거",
   licenseAndPolicy:"이용 약관 & 개인 정보 보호 정책",
 }
});

exports.string = MHLocalizableString
